"""Composable satellite attitude models and methods."""

from satmodel._version import __version__
from satmodel.actuators import (
    ReactionWheelArrayConfig,
    ReactionWheelConfig,
    ReactionWheelStateEffector,
    TorqueActuator,
    TorqueActuatorConfig,
)
from satmodel.controllers import LADRCConfig, LADRCController, PDController
from satmodel.dynamics import RK4Integrator, SpacecraftDynamics
from satmodel.disturbances import (
    AerodynamicTorque,
    AerodynamicTorqueConfig,
    GravityGradientTorque,
    GravityGradientTorqueConfig,
    DisturbanceEffectorSet,
    ResidualMagneticTorque,
    ResidualMagneticTorqueConfig,
    SolarPressureTorque,
    SolarPressureTorqueConfig,
    default_leo_disturbance_effectors,
)
from satmodel.environment import (
    AtmosphereModel,
    CenteredDipoleMagneticField,
    CircularOrbitProvider,
    EnvironmentConfig,
    EnvironmentModel,
    EphemerisOrbitProvider,
    ExponentialAtmosphere,
    IGRFMagneticField,
    KeplerianOrbitProvider,
    MagneticFieldModel,
    NRLMSISAtmosphere,
    OrbitProvider,
    OrbitalEnvironment,
    SpaceWeatherInputs,
    TLEOrbitProvider,
    ZeroEnvironment,
    build_demo_leo_environment,
    geodetic_from_eci,
)
from satmodel.estimation import EstimatorStack, MEKF, MEKFConfig
from satmodel.geometry import BoxGeometry
from satmodel.identification import (
    RLSConfig,
    RLSIdentifier,
    TrackingDifferentiator,
    build_inertia_regression_matrix,
)
from satmodel.optimization import (
    GridSearchOptimizer,
    NelderMeadOptimizer,
    OptimizationResult,
    PSOOptimizer,
    RandomSearchOptimizer,
    SimulatedAnnealingOptimizer,
)
from satmodel.physics import CubeSatPhysicalConfig, MassProperties, cubesat_demo_mass_properties, uniform_box_inertia
from satmodel.sensors import AttitudeSensor, GyroSensor, SensorSuite
from satmodel.system import SatelliteSystem, ScenarioRunner, build_cubesat_reaction_wheel_system, build_default_system
from satmodel.types import (
    EnvironmentContext,
    EstimatedState,
    GeodeticPoint,
    OrbitState,
    ReferenceAttitude,
    RigidBodyState,
    SensorMeasurement,
    SimulationConfig,
    SimulationResult,
    TorqueBudget,
    WheelArrayTelemetry,
)

__all__ = [
    "__version__",
    "AerodynamicTorque",
    "AerodynamicTorqueConfig",
    "AttitudeSensor",
    "AtmosphereModel",
    "BoxGeometry",
    "CenteredDipoleMagneticField",
    "CircularOrbitProvider",
    "CubeSatPhysicalConfig",
    "DisturbanceEffectorSet",
    "EnvironmentConfig",
    "EnvironmentModel",
    "EnvironmentContext",
    "EphemerisOrbitProvider",
    "EstimatedState",
    "EstimatorStack",
    "ExponentialAtmosphere",
    "GeodeticPoint",
    "GyroSensor",
    "GridSearchOptimizer",
    "GravityGradientTorque",
    "GravityGradientTorqueConfig",
    "IGRFMagneticField",
    "KeplerianOrbitProvider",
    "LADRCConfig",
    "LADRCController",
    "MagneticFieldModel",
    "MassProperties",
    "MEKF",
    "MEKFConfig",
    "NRLMSISAtmosphere",
    "NelderMeadOptimizer",
    "OptimizationResult",
    "OrbitProvider",
    "OrbitState",
    "OrbitalEnvironment",
    "PDController",
    "PSOOptimizer",
    "RK4Integrator",
    "RandomSearchOptimizer",
    "RLSConfig",
    "RLSIdentifier",
    "ReferenceAttitude",
    "ReactionWheelArrayConfig",
    "ReactionWheelConfig",
    "ReactionWheelStateEffector",
    "RigidBodyState",
    "ResidualMagneticTorque",
    "ResidualMagneticTorqueConfig",
    "SatelliteSystem",
    "ScenarioRunner",
    "SensorMeasurement",
    "SensorSuite",
    "SimulationConfig",
    "SimulationResult",
    "SimulatedAnnealingOptimizer",
    "SolarPressureTorque",
    "SolarPressureTorqueConfig",
    "SpacecraftDynamics",
    "SpaceWeatherInputs",
    "TLEOrbitProvider",
    "TorqueActuator",
    "TorqueActuatorConfig",
    "TorqueBudget",
    "TrackingDifferentiator",
    "ZeroEnvironment",
    "WheelArrayTelemetry",
    "build_cubesat_reaction_wheel_system",
    "build_default_system",
    "build_demo_leo_environment",
    "default_leo_disturbance_effectors",
    "build_inertia_regression_matrix",
    "cubesat_demo_mass_properties",
    "geodetic_from_eci",
    "uniform_box_inertia",
]
